services:
  nginx:
    container_name: github-nginx
    build:
      context: .
      dockerfile: /docker/local/nginx/Dockerfile
    volumes:
      - ./docker/local/nginx/conf:/etc/nginx/conf.d
    ports:
      - '80:80'

  api:
    container_name: github-api
    build:
      context: .
      dockerfile: /docker/local/php-fpm/Dockerfile
    volumes:
      - './api:/api'

  database:
    container_name: github-db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - github-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root


volumes:
  github-data:



  # mysql